[tool.poetry]
name = "jetscape_an"
version = "0.1.0"
description = "JETSCAPE analysis framework"
authors = ["Raymond Ehlers <raymond.ehlers@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
awkward1 = "^0.3.1"
uproot4 = "^0"
numpy = "^1.19.2"
pyarrow = "^1.0.1"
pyfastjet = {path = "../../pyfastjet"}
pandas = "^1.1.3"
particle = "^0.12.0"
numba = "^0.51.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^20.8b1"
mypy = "^0.782"
ipython = "^7.18.1"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
