[tool.poetry]
name = "mammoth"
version = "0.1.0"
description = "Mostly columnar based physics analyses"
authors = ["Raymond Ehlers <raymond.ehlers@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
awkward = "^1.2rc2"
uproot = "^4"
numpy = "^1.20"
pyarrow = "^4"
#pyfastjet = {path = "external/pyfastjet"}
pachyderm = {path = "external/pachyderm"}
pandas = "^1.2"
particle = "^0.14.0"
numba = {version = "^0.52.0", python = ">=3.7,<3.9"}
hist = {version = "^2.1", extras = ["plot"]}
seaborn = "^0.11.1"
vector = "^0.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^21.6b0"
mypy = "^0.902"
ipython = "^7.18.1"
pytest = "^6.2.4"

[tool.black]
line-length = 120
target-version = ["py38"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
