[tool.poetry]
name = "mammoth"
version = "0.1.0"
description = "Mostly columnar based physics analyses"
authors = ["Raymond Ehlers <raymond.ehlers@gmail.com>"]
license = "BSD-3-Clause"
include = [
    "mammoth/py.typed",
]

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
awkward = ">=1.7"
uproot = ">=4.2"
numpy = ">=1.21"
pyarrow = ">=4"
#pyfastjet = {path = "external/pyfastjet"}
# NOTE: Usually need to comment this out when trying to install in external projects.
#       This is necessary because pip can't seem to determine the location of dependency.
#       I'm not sure why, but it causes lots of problems
pachyderm = {path = "external/pachyderm", develop = true}
pandas = ">=1.3"
particle = ">=0.15.1"
numba = ">=0.55.2"
hist = {version = ">=2.5.0", extras = ["plot"]}
seaborn = ">=0.11.2"
vector = ">=0.8.5"
parsl = {git = "https://github.com/Parsl/parsl.git", rev = "6d1f9160d487b3265f6e9d65ebb357837a437c30", extras = ["monitoring"]}
rich = ">=11.2"
ninja = ">=1.10"

[tool.poetry.group.dev.dependencies]
flake8 = ">=3.8.3"
black = ">=22.1.0"
mypy = ">=0.931"
ipython = ">=8.0"
pytest = ">=6.2.4"
flake8-colors = ">=0.1.9"
ipykernel = ">=6.15.1"

[tool.black]
line-length = 120
target-version = ["py38"]

[tool.pytest.ini_options]
log_cli_level = "info"

[build-system]
requires = ["poetry_core>=1.1.0", "setuptools>=42", "ninja", "cmake>=3.15"]
build-backend = "poetry.core.masonry.api"
