[tool.poetry]
name = "mammoth"
version = "0.1.0"
description = "Mostly columnar based physics analyses"
authors = ["Raymond Ehlers <raymond.ehlers@gmail.com>"]
license = "BSD-3-Clause"
include = [
    "mammoth/py.typed",
]

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
awkward = "^1.5.1"
uproot = "^4.1.5"
numpy = "^1.21.0"
pyarrow = "^4"
#pyfastjet = {path = "external/pyfastjet"}
# NOTE: Usually need to comment this out when trying to install in external projects.
#       This is necessary because pip can't seem to determine the location of dependency.
#       I'm not sure why, but it causes lots of problems
pachyderm = {path = "external/pachyderm", develop = true}
pandas = "^1.3.0"
particle = "^0.15.1"
numba = "^0.53.1"
hist = {version = "^2.5.1", extras = ["plot"]}
seaborn = "^0.11.1"
vector = "^0.8"
parsl = {git = "https://github.com/Parsl/parsl.git", rev = "9eca2a949471520f161a82cc046397a1d69d939c", extras = ["monitoring"]}
rich = "^10.7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^21.6b0"
mypy = "^0.910"
ipython = "^7.25.0"
pytest = "^6.2.4"
flake8-colors = "^0.1.9"

[tool.black]
line-length = 120
target-version = ["py38"]

[build-system]
requires = ["poetry_core>=1.0.0", "setuptools>=42", "cmake>=3.14"]
build-backend = "poetry.core.masonry.api"
