[tool.poetry]
name = "jetscape_an"
version = "0.1.0"
description = "JETSCAPE analysis framework"
authors = ["Raymond Ehlers <raymond.ehlers@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
awkward1 = "^0.3.1"
uproot4 = "^0"
numpy = "^1.19.2"
pyarrow = "^1.0.1"
pyfastjet = {path = "../python_bindings/fastjet"}

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^20.8b1"
mypy = "^0.782"
ipython = "^7.18.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
